# Generated by Django 2.1 on 2019-09-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='totalPrice',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='Quant',
        ),
        migrations.AddField(
            model_name='order',
            name='completed_order',
            field=models.BooleanField(default=False),
        ),
    ]
